baseURL = "https://bbcbreno.github.io/hugo-hello/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-sustain"
publishDir = "docs"
[Params]
author = "Breno Caldeira"
avatar = "breno.jpg"
custom_css = ["css/custom.css"]
